version: "2.1"

services:
  conversor:
    image: maven:3-jdk-8-alpine
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: ["sh", "redeploy.sh"]